[tool.black]
target-version = ['py38', 'py39', 'py310']
skip-string-normalization = false
line-length = 79
exclude = '''
(
  /(
    | _build
    | buck-out
    | examples
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79


[tool.ruff]
line-length = 79
exclude = ["__init__.py","build",".eggs"]
