repos:
-   repo: https://github.com/python/black
    rev: 22.1.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      pass_filenames: true
# Sort order of Python imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
# Remove whitespace at line end, ensure newline at the end of files
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
