[project]
name = "{{cookiecutter.package_name}}"
version = "0.0.1"
authors = ["{{cookiecutter.full_name}} <{{cookiecutter.email}}>"]
description = "{{cookiecutter.short_description}}"
readme = "README.md"
requires-python = ">=3.8.0"

{% if cookiecutter.github_repository_url != 'provide later' -%}
url = "{{ cookiecutter.github_repository_url }}"
{%- endif %}
{% if cookiecutter.license == "MIT" -%}
license = "{{cookiecutter.license}}"
{%- elif cookiecutter.license == "BSD-3" -%}
license = "BSD-3-Clause"
{%- elif cookiecutter.license == "GNU GPL v3.0" -%}
license = "GPL-3.0-only"
{%- elif cookiecutter.license == "GNU LGPL v3.0" -%}
license = "LGPL-3.0-only"
{%- elif cookiecutter.license == "Apache Software License 2.0" -%}
license = "Apache-2.0"
{%- elif cookiecutter.license == "Mozilla Public License 2.0" -%}
license = "MPL-2.0"
{%- endif %}

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    {% if cookiecutter.license == "MIT" -%}
    "License :: OSI Approved :: MIT License",
    {%- elif cookiecutter.license == "BSD-3" -%}
    "License :: OSI Approved :: BSD License",
    {%- elif cookiecutter.license == "GNU GPL v3.0" -%}
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    {%- elif cookiecutter.license == "GNU LGPL v3.0" -%}
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    {%- elif cookiecutter.license == "Apache Software License 2.0" -%}
    "License :: OSI Approved :: Apache Software License",
    {%- elif cookiecutter.license == "Mozilla Public License 2.0" -%}
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    {%- endif %}
]

{% if cookiecutter.github_repository_url != 'provide later' -%}
[project.urls]
bug_tracker = "https://github.com/{{cookiecutter.github_username_or_organization}}/{{cookiecutter.package_name}}/issues"
documentation = "https://github.com/{{cookiecutter.github_username_or_organization}}/{{cookiecutter.package_name}}"
source_code = "https://github.com/{{cookiecutter.github_username_or_organization}}/{{cookiecutter.package_name}}"
user_support = "https://github.com/{{cookiecutter.github_username_or_organization}}/{{cookiecutter.package_name}}/issues"
{%- endif %}

[options.extras_require]
dev = [
	"black",
	"pytest",
	"pytest-cov",
	"bump2version",
	"pre-commit",
	"flake8",
	"coverage",
]



[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"




[tool.setuptools.packages]
find = {}  # Scanning implicit namespaces is active by default

[tool.setuptools.packages.find]
where = ["{{cookiecutter.module_name}}"]
exclude = ["{{cookiecutter.package_name}}.test*"]

[tool.pytest.ini_options]
addopts = "--cov={{cookiecutter.package_name}}"

[tool.black]
target-version = ['py39']
skip-string-normalization = false
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | examples
  )/
)
'''
