name: Trigger a scheduled test
on:
  push: # temporary
  workflow_dispatch: # For occasional manual triggering e.g. for debugging
  schedule:
    - cron: "0 3 * * 0" # Every Sunday at 3 AM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger testing workflow
        if: github.repository_owner == 'neuroinformatics-unit' # don't trigger scheduled run from forks
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.neuroinformatics-unit,
              repo: context.repo.python-cookiecutter,
              workflow_id: 'test.yml',
              ref: 'main',
            })
